baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme                            = "themes/introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[services]
  [services.googleAnalytics]
    ID = 'GTM-NC2CQVBQ'

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "https://kit.fontawesome.com/8248f4cea0.js" #/img/fav.ico"          # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    #email                        = "s.grasso@dr-i.tech"   # E-mail address for contact section
    # customCSS                  = ["foo.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Paris"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-UK"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
    	twitter = "stefano_beowulf"
        url   = "https://x.com/stefano_beowulf"
        icon  = "x-twitter" # icon name without the 'fa-'
        icon_pack = "fab"
#    [[params.social]]
#        url   = "https://facebook.com/"
#        icon  = "facebook-f" # icon name without the 'fa-'
#        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/stefano-grasso-biotech/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:s.grasso@dr-i.tech"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"
    [[params.social]]
        url   = "https://github.com/grassoste"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
       # html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification
    [[params.social]]
        url   = "https://www.researchgate.net/profile/Stefano-Grasso"
        icon  = "researchgate" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://scholar.google.com/citations?user=ZYXEuS0AAAAJ&hl=en"
        icon  = "google-scholar" # icon name without the 'fa-'
        icon_pack = "fab"


# If you don't want to use the default menu, you can define one by yourself
#[menu]
# [[menu.main]]
#     name    = "X"
#     url     = "/Social#xtwitter"
#     parent  = "Social"
# [[menu.main]]
#     name    = "Social"
#     url     = "/Social/"
#     weight  = 7

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Introduction"
        [languages.en.params]
            description  = "Stefano Grasso's professional and personal website"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)

    [languages.it]
        languageName     = "Italiano"
        languageCode     = "it"
        contentDir       = "content/it"
        weight           = 1
        title            = "Introduzione"
        [languages.it.params]
            description  = "Sito web professionale e personale di Stefano Grasso"
            # footerText   = ""

